@startuml
vendég -> (hely kérvényezése a recepcióstól)
(hely kérvényezése a recepcióstól) ..> (kérhet plusz költséges dolgokat)
(hely kérvényezése a recepcióstól) -> :recepciós:
(kérhet plusz költséges dolgokat)  .> :recepciós:
:recepciós: --> (lekérdezheti az üres helyeket \n adott intervallumon belül)

:recepciós: --> (kiadhat helyet a vendégnek)
:recepciós: --> (foglalhat le helyet a vendégnek )
:recepciós: -->(a recepciós számlát állít ki\n a vendég távozáskor)
@enduml